export const SET_DATA = 'SET_DATA';
export const SET_THEME = 'SET_THEME';
export const START_DATA_LOADING = 'START_DATA_LOADING';
export const DATA_LOADING_SUCCESS = 'DATA_LOADING_SUCCESS';
export const DATA_LOADING_FAILURE = 'DATA_LOADING_FAILURE';

export const INCREASE_USER_SCORE = 'INCREASE_USER_SCORE';
export const RESET_USER_SCORE = 'RESET_USER_SCORE';

export const USER_REGISTER = 'USER_REGISTER';
export const COMPLETE_QUIZ = 'COMPLETE_QUIZ';
export const RESET_STATS = 'RESET_STATS';
